### ISSUE TITLE
Packages names and publish in NPM

### ISSUE THREAD

**Issue by ramonxm** [estartando-devs/ed-ui#71]
<img width="342" alt="image" src="https://user-images.githubusercontent.com/38158476/163815020-6628584a-fef1-4a3c-9f59-98c59aee0f54.png">
 

No NPM, está esse nome, seria interessante discutir um tipo `@ed-ui/react`, com a ideia de ser agnostico teria o `@ed-ui/styles` para o css apenas. O que acha?

E fazer ele full ts já tipado pra não precisar ficar fazendo `@types/ed-ui`.

**Comment by ramonxm** [comment]
@jonataspinto

**Comment by jonataspinto** [comment]
De acordo! Podemos inclusive publicar com GH packages
